### PR TITLE
Project settings provider env tests

### LINKED ISSUE #108: Port/write tests for ProjectSettingsProviderEnv
Tests for code ported as part of Issue #63

### PR DESCRIPTION
**Pull request by baumatron**
Fix #108

### CODE REVIEW

**Comment by baumatron** [comment]
Do we have opinions on whether I should squash and merge or do a merge commit for this? I like to use many logical commits to make the review easier to follow, but not sure if that history is useful to keep around once the topic branch is blown away.

**Comment by masojus** [comment]
Whatever you think is a logical/meaningful set of commits.

**Comment by masojus** [comment]
I'd prefer at least a merge commit, but "Squash & Merge" will actually fast forward which I'm against.

**Comment by masojus** [comment]
Oh and It'd be nice to merge the Travis CI change first.

**Comment by baumatron** [comment]
Lol. I removed some unnecessary code so code coverage went down. Oh well.

**Comment by baumatron** [comment]
Post merge build from my fork: https://travis-ci.org/baumatron/keen-sdk-net/builds/260398765

**Pull request merged**
