### PR TITLE
[WIP] Port Event cache portable

### LINKED ISSUE #65: Port/rewrite EventCachePortable for new netstandard PCL
This class is broken, and references API's that don't seem to be included in the netstandard API surface. First, confirm that the API's it relies on aren't included in netstandard2.0. If that's the case, it needs to be re-written targeting a netstandard API surface, along with robust unit tests. Otherwise, fix it and provide some good unit tests.

See https://github.com/keenlabs/keen-sdk-net/issues/21

### PR DESCRIPTION
**Pull request by Donistivanov**
Works at least to the extent of known race conditions

Is based off https://github.com/keenlabs/keen-sdk-net/pull/103

look to
close #65

### CODE REVIEW

**Comment by Donistivanov** [comment]
What is the proper way to debug this failed build?

**Comment by masojus** [comment]
@Donistivanov Normally you would just look at the logs linked to by the "Details" link, but I'm not sure if you have permission to view those. Are you able to see what it spits out here? https://ci.appveyor.com/project/masojus/keen-sdk-net/build/1.0.37-dotnetsummer

Of course, if it's an issue with all the changes I've been making and the netstandard build and the `dotnet build` vs `msbuild` issues (which is likely) then it's up to your DevOps guy (me) to fix it. I would only worry if you see actual compilation errors referring to something to do with the `EventCachePortable` or other code you touched in this change.  This APpVeyor setup is brand new and we're evolving it side by side with the addition of the NetStandard binaries, so some rough patches are expected :)

**Comment by jongalloway** [comment]
The appveyor build logs are public by default. Direct to this build log: [https://ci.appveyor.com/project/masojus/keen-sdk-net/build/1.0.37-dotnetsummer](https://ci.appveyor.com/project/masojus/keen-sdk-net/build/1.0.37-dotnetsummer)

**Comment by Donistivanov** [comment]
Yes I can. It was weird that using the original PCL package made everything build on my computer. I will mark this as WIP for now since there may be more to this than I initially saw.

**Comment by masojus** [comment]
@jongalloway Yeah that's what I figured. It's what @baumatron had posited in Issue #65

**Comment by masojus** [comment]
@Donistivanov I would pick Immo's brain in Slack. This is likely due to the version of `msbuild` used by VS 2017 vs the `dotnet build`/`dotnet msbuild` commands is different. It could also be the version mismatch between your machine (VS 15.3 preview) and AppVeyor's VS 2017 version (15.1)

**Comment by masojus** [comment]
The real question is *should* PCLStorage build in a netstandard project, and my expectation was that, no, it wouldn't due to portability analysis reports, but I was remaining optimistic :)

**Comment by masojus** [comment]
I'm holding off on merging this one until we get a better idea of what is expected with `PCLStorage` vs `PCLStorage.Standard` and get this working as expected with the VS 15.3 tools. @Donistivanov feel free to update from `master` and push a new change to see if the recent CI config changes make any difference. If things are still looking broken, then let's try out the `PCLStorage.Standard` nuget package, and whatever changes that implies to adapt to its interfaces, as long as they don't seem extensive. If this starts looking to be a headache, considering the existing bugs and potential re-write of this class, I'd shelve it for now.

**Comment by Donistivanov** [comment]
I am closing this pull request in favor of the work at https://github.com/keenlabs/keen-sdk-net/pull/121

**Pull request closed without merging**
